# Generated by Django 6.0.6 on 2026-07-02 02:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科目名称')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目管理',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='试卷标题')),
                ('description', models.TextField(blank=True, default='', verbose_name='考试说明')),
                ('duration', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(600)], verbose_name='考试时长（分钟）')),
                ('total_marks', models.DecimalField(decimal_places=1, default=100, max_digits=6, verbose_name='总分')),
                ('pass_score', models.DecimalField(decimal_places=1, default=60, max_digits=6, verbose_name='及格分')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('finished', '已结束')], default='draft', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='得分')),
                ('total_marks', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='总分')),
                ('correct_count', models.IntegerField(default=0, verbose_name='正确数')),
                ('wrong_count', models.IntegerField(default=0, verbose_name='错误数')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('duration_used', models.IntegerField(default=0, verbose_name='用时（秒）')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam', verbose_name='试卷')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '考试成绩',
                'verbose_name_plural': '考试成绩管理',
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'exam')},
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('single', '单选题'), ('multiple', '多选题'), ('judge', '判断题')], default='single', max_length=10, verbose_name='题型')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项')),
                ('correct_answer', models.JSONField(verbose_name='正确答案')),
                ('difficulty', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='答案解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='出题人')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.subject', verbose_name='所属科目')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题库管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=1, default=5, max_digits=5, verbose_name='分值')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam', verbose_name='试卷')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='题目')),
            ],
            options={
                'verbose_name': '试卷题目',
                'verbose_name_plural': '试卷题目管理',
                'ordering': ['order'],
                'unique_together': {('exam', 'question')},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(through='exams.ExamQuestion', to='exams.question', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.subject', verbose_name='所属科目'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_answer', models.JSONField(blank=True, default=list, verbose_name='学生答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确')),
                ('marks_obtained', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='得分')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='题目')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examresult', verbose_name='考试结果')),
            ],
            options={
                'verbose_name': '答题记录',
                'verbose_name_plural': '答题记录管理',
                'unique_together': {('result', 'question')},
            },
        ),
    ]
